name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1' # Lunes a las 3 AM, escaneo semanal automático

jobs:
  # --- Job 1: Escaneo de dependencias OWASP ---
  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest

      # Práctica recomendada: definir permisos explícitamente para seguridad
    permissions:
      contents: read # Necesario para hacer checkout del código
      actions: read  # Permite que las acciones funcionen correctamente

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@v4
        with:
          project: 'SpringBootApp'
          path: '.'
          format: 'HTML'
          out: 'reports'

      - name: Upload OWASP report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: reports
          retention-days: 7

  # --- Job 2: Análisis estático con CodeQL ---
  codeql-analysis:
    name: Static Code Analysis (CodeQL)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild project
        uses: github/codeql-action/autobuild@v3

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:${{ matrix.language }}'
